/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateSampleArgs } from "./CreateSampleArgs";
import { UpdateSampleArgs } from "./UpdateSampleArgs";
import { DeleteSampleArgs } from "./DeleteSampleArgs";
import { SampleFindManyArgs } from "./SampleFindManyArgs";
import { SampleFindUniqueArgs } from "./SampleFindUniqueArgs";
import { Sample } from "./Sample";
import { SampleService } from "../sample.service";

@graphql.Resolver(() => Sample)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class SampleResolverBase {
  constructor(
    protected readonly service: SampleService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Sample",
    action: "read",
    possession: "any",
  })
  async _samplesMeta(
    @graphql.Args() args: SampleFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Sample])
  @nestAccessControl.UseRoles({
    resource: "Sample",
    action: "read",
    possession: "any",
  })
  async samples(@graphql.Args() args: SampleFindManyArgs): Promise<Sample[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Sample, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Sample",
    action: "read",
    possession: "own",
  })
  async sample(
    @graphql.Args() args: SampleFindUniqueArgs
  ): Promise<Sample | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Sample)
  @nestAccessControl.UseRoles({
    resource: "Sample",
    action: "create",
    possession: "any",
  })
  async createSample(@graphql.Args() args: CreateSampleArgs): Promise<Sample> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Sample)
  @nestAccessControl.UseRoles({
    resource: "Sample",
    action: "update",
    possession: "any",
  })
  async updateSample(
    @graphql.Args() args: UpdateSampleArgs
  ): Promise<Sample | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Sample)
  @nestAccessControl.UseRoles({
    resource: "Sample",
    action: "delete",
    possession: "any",
  })
  async deleteSample(
    @graphql.Args() args: DeleteSampleArgs
  ): Promise<Sample | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
